T({
	language : {
		en : 'English',
		ko : 'Korean',
		cn : 'Chinese'
	},

	menu : {
		user : 'User',
		directory : 'Directory',
		diagram : 'Diagram',
		diagram_definition : 'Diagram Definition',
		favorite : 'Favorite',
		profile : 'User Profile'
	},
	
	title : {
		confirmation : 'Confirmation',
		information : 'Information',
		search_condition : 'Search Condition',
		details : 'Details',
		resource_list : '{resource} List',
		resource_details : '{resource} Details',
		user : 'User',
		user_list : 'User List',
		user_details : 'User Details',
		directory : 'Directory',
		diagram : 'Diagram',
		diagram_definition : 'Diagram Definition',
		favorite : 'Favorite'
	},
	
	tab : {
		grid_view : 'Grid View',
		list_view : 'List View'		
	},
	
	button : {
		new : 'New',
		search : 'Search',
		reset : 'Reset',
		save : 'Save',
		add : 'Add',
		del : 'Delete',
		cancel : 'Cancel',
		sync : 'Sync',
		file : 'file...',
		open : 'Open',
		close : 'Close',
		change : 'Change',
		select : 'Select',
		list : 'List'
	},
	
	label : {
		last_released_version : 'Last Released Version',
		current_version : 'Current Version',
		cv_status : 'Current Version Status',
		parent_id : 'Parent Id',
		version : 'Version',
		directory_id : 'Directory Id',
		keyword : 'Keyword',
		default_domain : 'Default Domain',
		summary : 'Summary',
		language : 'Language',
		success : 'Success',
		failure : 'Failure',
		movie : 'Movie',
		id : 'ID',
		name : 'Name',
		description : 'Description',
		created_at : 'Created At',
		updated_at : 'Updated At',
		created_at_from : 'Created At From',
		created_at_to : 'Created At To',
		updated_at_from : 'Created At From',
		updated_at_to : 'Updated At To',
		date : 'Date',
		image_upload : 'Image Upload',
		timezone : 'Timezone',
		email : 'E-Mail',
		sur_name : 'Sur Name',
		nick_name : 'Nick Name',
		for_name : 'For Name',
		enabled : 'Enabled',
		admin : 'Admin',
		locale : 'Locale',
		company : 'Company',
		group : 'Group',
		code : 'Code',		
		autofit : 'Autofit',
		refreshterm : 'Refresh Every',
		location : 'Location',		
		image : 'Image',
		driving : 'Driving',
		reg_no : 'Reg. No.',
		status : 'Status',
		latitude : 'Latitude',
		longitude : 'Longitude',
		latitude_min  : 'Min. Lat.',
		longitude_min : 'Min. Lng',
		latitude_max  : 'Max. Lat',
		longitude_max : 'Max. Lng',	
		confirm : 'Confirm',
		video_upload : 'Video Upload',
		datetime : 'Date/Time',
		running : 'Running',
		start : 'Start',
		end : 'End',
		division : 'Division',
		title : 'Title',
		social_id : 'Social Id',
		serial : 'Serial',
		comment : 'Comment',
		destination : 'Destination',
		purpose : 'Purpose',
		item : 'Item',
		cost : 'Cost',
		worker : 'Worker',
		component : 'Component',
		time : 'Time',
		year : 'Year',
		month : 'Month',
		distance : 'Distance',
		type : 'Type',
		total : 'Total',
		content : 'Content',		
		address : 'Address',			
		alarm : 'Alarm',
		event_type : 'Event Type',
		event_name : 'Event',
		event_trigger : 'Event Trigger',
		send_to : 'Send to',
		message : 'Message',
		from_date : 'From Date',
		to_date : 'To Date',
		from_time : 'From Time',
		to_time : 'To Time',
		times : 'Times',		
		second_s : 'sec.',
		minute_s : 'min.',
		parentheses_year : '(year)',
		parentheses_month : '(month)',
		parentheses_day : '(day)',
		parentheses_hour : '(hour)',
		parentheses_min : '(min)',
		period_always : 'Period Always',
		period : 'Period',
		chart : 'Chart',
		view : 'View',
		monthly_view : 'Monthly View',
		yearly_view : 'Yearly View',
		chart_type : 'Chart Type',
		line : 'Line',
		column : 'Column',
		radar : 'Radar',
		sum : 'Sum',
		setting : 'Setting',
		dockPosition : 'Docking Position',
		left : 'Left',
		right : 'Right',
		grade : 'Grade',
		daily : 'Daily',
		weekly : 'Weekly',
		monthly : 'Monthly',
		yearly : 'Yearly',
		notifiable_flag : 'Notifiable',
		editable_flag : 'Editable',
		indexible_flag : 'Indexible',
		at : 'At',
		file_path : 'Require Name',
		retry_count : 'Retry Count',
		error : 'Error',
		url : 'URL',
		user_id : 'User Id',
		title_image_path : 'Title Image',
		movie_path : 'Movie',
		image_path : 'Image'
	},
	
	format : {
		date : 'Y-m-d',
		time : 'H:i:s',
		datetime : 'Y-m-d H:i:s'
	},
	
	msg : {
		searching : 'Searching ...',
		saving : 'Saving Data...',
		no_matching_data_found : 'No matching data found!',
		confirm_save : 'Would you like to save?',
		confirm_delete : 'Would you like to delete?',
		confirm_do : 'Would you like to {do}?',
		confirm_run : 'Would you like to run?',
		processed_successfully : 'Have been processed successfully.',
		failed_to_save : 'Failed to save!',
		failed_to_delete : 'Failed to delete!',
		failed_to_validate : 'Failed to validate!',
		failed_to_do : 'Failed to {do}!',
		failed_to_ajax : 'Ajax communication failed!',
		invalid_form_values : 'Form fields may not be submitted with invalid values!',
		select_users : 'Enter email addresses of users that you want to send an alarm, separated by , ...',
		no_data_changed : 'No data changed!',
		none_selected : 'None Selected!',
		select_x_first : 'Select {x} First!',
		paging_display_msg : 'Displaying {name} {0} - {1} of {2}',
		paging_empty_msg : 'No {name} to display'
	}
});