T({
	language : {
		en : '영어',
		ko : '한국어',
		cn : '중국어'
	},
	
	menu : {
		user : '사용자',
		directory : '디렉토리',
		diagram : '다이어그램',
		diagram_definition : '다이어그램 정의',
		favorite : '즐겨찾기',
		profile : '사용자 프로파일'
	},
	
	title : {
		confirmation : '확인',
		information : '정보',
		search_condition : '검색 조건',
		details : '상세',
		resource_list : '{resource} 리스트',
		resource_details : '{resource} 상세',		
		user : '사용자',
		user_list : 'User 리스트',
		user_details : 'User 상세',
		directory : '디렉토리',
		diagram : '다이어그램',
		diagram_definition : '다이어그램 정의',
		favorite : '즐겨찾기'
	},
	
	tab : {
		grid_view : '그리드 보기',
		list_view : '리스트 보기'
	},
	
	button : {
		new : '생성',
		search : '검색',
		reset : '초기화',
		save : '저장',
		add : '추가',
		del : '삭제',
		cancel : '취소',
		sync : '동기화',
		file : '파일...',
		open : '열기',
		close : '닫기',
		change : '변경',
		list : '리스트'
	},
	
	label : {
		last_released_version : '최근 배포 버전',
		current_version : '현재 버전',
		cv_status : '현재 버전 상태',
		parent_id : '부모 Id',
		version : '버전',
		directory_id : '디렉토리 Id',
		keyword : '키워드',
		default_domain : '기본 도메인',
		summary : '서머리',
		language : '언어',
		success : '성공',
		failure : '실패',
		movie : '동영상',
		id : '아이디',
		name : '이름',
		description : '설명',
		created_at : '생성일',
		updated_at : '수정일',
		created_at_from : '생성일 From',
		created_at_to : '생성일 To',
		updated_at_from : '수정일 From',
		updated_at_to : '생성일일 To',
		date : '일자',
		image_upload : '사진 업로드',
		timezone : '타임존',
		email : '이메일',
		sur_name : '성',
		nick_name : '별명',
		for_name : '이름',
		enabled : '사용가능',
		admin : '관리자',
		locale : '지역',
		company : '회사',
		group : '그룹',
		code : '코드',
		autofit : '자동맞춤',
		refreshterm : '갱신주기',
		location : '위치',		
		image : '사진',
		reg_no : '등록번호',		
		status : '상태',
		latitude : '위도',
		longitude : '경도',
		latitude_min  : '최소 위도',
		longitude_min : '최소 경도',
		latitude_max  : '최대 위도',
		longitude_max : '최대 경도',
		confirm : '확인',
		video_upload : '비디오 업로드',
		datetime : '일시',
		running : '운행중',
		start : '시작',
		end : '완료',
		division : '부서',
		title : '직책',
		social_id : '사회보장 아이디',
		serial : '일련번호',
		comment : '코멘트',
		destination : '행선지',
		purpose : '목적',
		item : '항목',
		cost : '비용',
		worker : '작업자',
		component : '컴포넌트',
		time : '시간',
		year : '년',
		month : '월',
		distance : '거리',
		type : '타입',
		total : '총',
		content : '내용',		
		address : '주소',
		alarm : '알람',		
		event_type : '이벤트 타입',
		event_name : '이벤트',
		event_trigger : '이벤트 트리거',
		send_to : '보내기 대상',
		message : '메세지',
		from_date : '시작일',
		to_date : '종료일',
		from_time : '시작시간',
		to_time : '종료시간',
		times : '횟수',
		second_s : '초',
		minute_s : '분',
		parentheses_year : '(년)',
		parentheses_month : '(개월)',
		parentheses_day : '(일)',
		parentheses_hour : '(시간)',
		parentheses_min : '(분)',
		period_always : '기간 항상',
		period : '기간',
		chart : '차트',
		view : '보기',
		monthly_view : '월별 보기',
		yearly_view : '년별 보기',
		chart_type : '차트 타입',		
		line : '라인',
		column : '컬럼',
		radar : '레이더',
		sum : '합계',
		setting : '설정',
		dockPosition : '현황패널 도킹 위치',
		left : '왼쪽',
		right : '오른쪽',
		grade : '등급',
		daily : '일별',
		weekly : '주별',
		monthly : '월별',
		yearly : '년별',
		notifiable_flag : '통지 여부',
		editable_flag : '편집 여부',
		indexible_flag : '인덱스 여부',
		at : '작업시간',
		file_path : 'Require Name',
		retry_count : '재시도 횟수',
		error : '에러메세지',
		url : 'URL',
		user_id : '사용자 ID',
		title_image_path : '타이틀 이미지',
		movie_path : '동영상',
		image_path : '이미지'
	},
	
	format : {
		date : 'Y-m-d',
		time : 'H:i:s',
		datetime : 'Y-m-d H:i:s'
	},
	
	msg : {
		searching : '검색중 ...',
		saving : '저장중...',
		no_matching_data_found : '해당되는 데이타가 없습니다!',
		confirm_save : '저장하시겠습니까?',
		confirm_delete : '삭제하시겠습니까?',
		confirm_do : '정말 {do}하시겠습니까?',
		confirm_run : '실행하시겠습니까?',
		processed_successfully : '정상적으로 처리되었습니다.',
		failed_to_save : '저장 실패했습니다!',
		failed_to_delete : '삭제 실패했습니다!',
		failed_to_validate : '유효성 검증에 실패했습니다!',		
		failed_to_do : '{do} 실패했습니다!',
		failed_to_ajax : 'Ajax 통신에 실패했습니다!',
		invalid_form_values : '폼 필드에 유효하지 않은 값이 있습니다',
		select_users : '알람을 보내고자 하는 사용자의 이메일 주소를 ,로 구분하여 입력...',
		no_data_changed : '변경된 데이터가 없습니다!',		
		none_selected : '선택된 항목이 없습니다!',
		select_x_first : '{x}를 먼저 선택해주세요',
		paging_display_msg : '{name} 리스트 {0} - {1} of {2}',
		paging_empty_msg : '{name} 데이터 없음'
	}
});